---
title: 'Logistic Regression: Widget Failure'
author: "Christopher Spaude"
date: "March 20, 2018"
output:
  word_document: default
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE, warning=FALSE, include=FALSE}
#Import libraries
library(readr)
library(dplyr)
library(ggplot2)
library(HH)
```

```{r message=FALSE, warning=FALSE, include=FALSE}
#function for building contingency table

contin_table <- function(df,thres){
#machine failed and model predicted fail
ff <- sum(df$prediction < thres & df$STATUS == "failed")
#machine failed but model predicted not fail
fn <- sum(df$prediction > thres & df$STATUS == "failed")
#machine not fail but model predicted fail
nf <- sum(df$prediction < thres & df$STATUS == "non-failed")
#machine not fail and model predicted not fail
nn <- sum(df$prediction > thres & df$STATUS == "non-failed")

print(matrix(data = c(ff,nf,fn,nn),nrow= 2,
       dimnames = list(c('Failed Widget','non-Failed Widget'),c('Predicted Fail','Predicted non-Failed'))))

return(list(ff=ff,fn=fn,nf=nf,nn=nn))
}
```

```{r eval=FALSE, message=FALSE, warning=FALSE, include=FALSE}
#List of terms:
  #data = original csv data
  #data1 = data after removing categorical variables
  #training_data = initial split of data1 for testing and training set
  #test_data = initial split of data1 for testing and training set
  #model1 = intial model, categorical variable removed
    #training_data1 = no transformation just keeping with naming convention
    #test_data1 = no transformation just keeping with naming convention
  #model2 = proportion and oversampled
  #model3 = proportion, oversampled, and important factors
```

##Exploring Data
```{r include=FALSE}
#import data
data <- read.csv(paste0(getwd(),"/Data/data.csv"))
```

```{r echo=FALSE}
summary(data)
```

```{r include=FALSE}
# Removing unimportant parameters
data1 <- data[,c(1,5:21)]
```

```{r echo=FALSE}
#Create additional column for total time
data1$TOTALTIME <- data1$MEASURE1+data1$MEASURE2+data1$MEASURE3+data1$MEASURE4+data1$MEASURE5+data1$MEASURE6+data1$MEASURE7+data1$MEASURE8+data1$MEASURE9+data1$MEASURE10+data1$MEASURE11+data1$MEASURE12+data1$MEASURE13+data1$MEASURE14+data1$MEASURE15+data1$MEASURE16+data1$MEASURE17

boxplot(TOTALTIME~STATUS,data = data1,main = "Total Operating Time",names = c("Failed Machines","Non-Failed Machines"))
data1 <- data1[,1:18]
```

```{r echo=FALSE, fig.height=11, fig.width=7}
par(mfrow=c(3,3))
for(i in 2:18){
  boxplot(data1[,i]~STATUS,data = data1,main = colnames(data1)[i],names = c("F","NF"))
}
```

```{r echo=FALSE}
median. <- data.frame(data1%>%
  group_by(STATUS)%>%
  summarise_all(.funs = median)%>%
  t())

colnames(median.) <- c(as.character(median.[1,1]),as.character(median.[1,2]))

print(median.[2:nrow(median.),])
rm(median.)
```

```{r include=FALSE}
#separating the data into a training and test set
set.seed(10)

training_rows <- sample(1:nrow(data1),size = ceiling(nrow(data1)*0.8))
training_data <- data1[training_rows,]
test_data <- data1[-training_rows,]
```

###Initial Model
```{r echo=FALSE, message=FALSE, warning=FALSE}
#build initial model before any data transformation
training_data1 <- training_data
model1 <- glm(STATUS~.,
             data = training_data1,
             family = "binomial")

#set up test data
test_data1 <- test_data
test_data1$prediction <- round(predict(model1,test_data1[,2:18],type = "response"),4)

#build contingency table
out <- contin_table(test_data1,0.5)
```

#III. Data Transformation
```{r echo=FALSE, fig.height=11, fig.width=7, message=TRUE, warning=TRUE}
#Convert training data to proportion of time

#calculate total time
training_data2 <- training_data
training_data2$tot_time <- rowSums(training_data2[,2:ncol(training_data2)])

#divide each bin by total time
for(i in 2:ncol(training_data2)){
  training_data2[,i] <- training_data2[,i]/training_data2$tot_time
}

#remove total time column
training_data2 <- training_data2[,1:ncol(training_data2)-1]
```

```{r echo=FALSE, fig.height=11, fig.width=7, message=TRUE, warning=TRUE}
#plot box plots with proportion of time
par(mfrow=c(3,3))
for(i in 2:18){
  boxplot(training_data2[,i]~STATUS,data = training_data2,main = colnames(training_data2)[i],names = c("F","NF"))
}
```

```{r include=FALSE}
#add 783 rows
training_data2_over <- data.frame(
  STATUS = rep('failed',783),
  MEASURE1 = numeric(783),
  MEASURE2 = numeric(783),
  MEASURE3 = numeric(783),
  MEASURE4 = numeric(783),
  MEASURE5 = numeric(783),
  MEASURE6 = numeric(783),
  MEASURE7 = numeric(783),
  MEASURE8 = numeric(783),
  MEASURE9 = numeric(783),
  MEASURE10 = numeric(783),
  MEASURE11 = numeric(783),
  MEASURE12 = numeric(783),
  MEASURE13 = numeric(783),
  MEASURE14 = numeric(783),
  MEASURE15 = numeric(783),
  MEASURE16 = numeric(783),
  MEASURE17 = numeric(783)
)
#resample from original training data
for(i in 2:ncol(training_data2_over)){
  training_data2_over[,i] <- sample(training_data2[training_data2$STATUS=='failed',i],size = 783,replace = TRUE)
}

training_data2 <- rbind(training_data2_over,training_data2)
rm(training_data2_over)
```

```{r echo=FALSE, warning=FALSE}
#build model with proportion over sampled data
model2 <- glm(STATUS~.,
             data = training_data2,
             family = "binomial")

#set up test data
test_data2 <- test_data
test_data2$tot_time <- rowSums(test_data2[,2:ncol(test_data2)])
for(i in 2:ncol(test_data2)){
  test_data2[,i] <- test_data2[,i]/test_data2$tot_time
}
test_data2 <- test_data2[,1:ncol(test_data2)-1]

#predict test data with model
test_data2$prediction <- round(predict(model2,test_data2[,2:18],type = "response"),4)

#output contigency table
out<- contin_table(test_data2,0.5)
```

#IV. Statistically Significant Measures
```{r include=FALSE}
step(model2,
     direction = "both")
```

```{r include=FALSE}
vif(model2)
```

```{r echo=FALSE, warning=FALSE}
training_data3 <- training_data2[,c("STATUS","MEASURE1",'MEASURE2','MEASURE4','MEASURE11','MEASURE12','MEASURE13','MEASURE14','MEASURE15','MEASURE16','MEASURE17')]

model <- glm(STATUS~.,
             data = training_data3,
             family = "binomial")

test_data3 <- test_data2[,c("STATUS","MEASURE1",'MEASURE2','MEASURE4','MEASURE11','MEASURE12','MEASURE13','MEASURE14','MEASURE15','MEASURE16','MEASURE17')]
test_data3$prediction <- predict(model,test_data3[,2:11],type = "response")

out <- contin_table(test_data3,0.5)
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
# hist(test_data3$prediction,main = "Histogram of Predicted Values",xlab = "Predicted Values")

thres_df <- data.frame(
  thres = seq(0.1,0.9,0.1),
  type1 = numeric(9),
  type2 = numeric(9)
)

for(i in 1:nrow(thres_df)){
  thres_df$type1[i] <- sum(test_data3$prediction > thres_df$thres[i] & test_data3$STATUS == "failed") 
  thres_df$type2[i] <- sum(test_data3$prediction < thres_df$thres[i] & test_data3$STATUS == "non-failed") 
}

par(mfrow = c(1,2))
plot(type1~thres,thres_df,main = "Type I Error Trade-Off",xlab = "Classification Threshold",ylab = "Number of Machines")
plot(type2~thres,thres_df,main = "Type II Error Trade-Off",xlab = "Classification Threshold",ylab = "Number of Machines")
```